GIT_REPO_URL: "https://github.com/TANISHKA-SINGLA/jenkins-ansible-shared-lib.git"
GIT_BRANCH: "main"

ANSIBLE_PLAYBOOK: "playbook.yml"
INVENTORY_FILE: "inventory.ini"

ENVIRONMENT: "prod"

SLACK_CHANNEL_NAME: "jenkins-alert"
ACTION_MESSAGE: "Consul deployment completed"
KEEP_APPROVAL_STAGE: true
